// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toowewpxzuihjiyomfej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvb3dld3B4enVpaGppeW9tZmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTQ5ODQsImV4cCI6MjA3MjU3MDk4NH0.jFtUXjhP90T8pYd_gpdqKuxo4afnzukLYuI3aXJ0esU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});